### PR TITLE
Issue #8: Initial JVM documentation.

### PR DESCRIPTION
**Pull request by joshua-rutherford**
As of now this simply alters the table of contents a bit and add the JVM installation instructions.  This covers all notes from @spmcbride1201 and @kaitmore on the setup and goes into far greater detail.  For now only macOS installation is covered but placeholders exist for Linux and Windows.

### CODE REVIEW

**Comment by joshua-rutherford** [comment]
@spmcbride1201 and @shanberg, I assume someone is going to handle any style issues.  If so @alecholmez you may want to work your style changes to your branch back in earlier rather than later.

**Comment by alecholmez** [comment]
@joshua-rutherford I've already worked some styling into the `initial` branch but nothing major. Just some stuff to increase readability

**Comment by joshua-rutherford** [comment]
@spmcbride1201 and @shanberg, start with @alecholmez pull request #14 then and once it's merged I'll rebase mine.  Mine really is just changes to the content directory when diffed with his.

**Comment by joshua-rutherford** [comment]
Moved to WIP until @alecholmez pr is merged and I rebase.

**Comment by joshua-rutherford** [comment]
@alecholmez, ok this is rebased on your commits and only contains JVM related content changes now.

**Pull request merged**
